export default [
  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2022-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2022-01-17",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2021-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2021-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-03-10",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-04-10",
  },
  {
    description: "Salário",
    amount: "20.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-05-10",
  },
  {
    description: "Salário",
    amount: "20.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-06-10",
  },
  {
    description: "Salário",
    amount: "2100.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-07-10",
  },
  {
    description: "Salário",
    amount: "2000.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-08-10",
  },
  {
    description: "Salário",
    amount: "2000.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-11-10",
  },
  {
    description: "Salário",
    amount: "2000.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-12-10",
  },
  {
    description: "Salário",
    amount: "200.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-09-10",
  },
  {
    description: "Salário",
    amount: "500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2021-10-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-05-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-06-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2023-07-10",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2022-02-22",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-02-20",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-03-20",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-03-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-03-10",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-03-2",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-02-2",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-02-10",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-03-11",
  },

  {
    description: "Freela app",
    amount: "450.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-04-2",
  },
  {
    description: "Freela app",
    amount: "200.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-04-20",
  },
  {
    description: "Freela app",
    amount: "200.92",
    type: "entrada",
    frequency: "eventual",
    date: "2023-04-22",
  },

  {
    description: "Freela app",
    amount: "300.92",
    type: "saída",
    frequency: "recorrente",
    date: "2023-04-23",
  },

  {
    description: "Freela Site",
    amount: "400.92",
    type: "saída",
    frequency: "eventual",
    date: "2023-04-25",
  },

  {
    description: "Contas",
    amount: "500.92",
    type: "saída",
    frequency: "eventual",
    date: "2023-04-26",
  },

  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2022-04-23",
  },
];
